// <auto-generated />
using BackupGateway.Web.Data.Model;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackupGateway.Web.Data.Migrations;

[DbContext(typeof(BackupGatewayDbContext))]
internal sealed class BackupGatewayDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity<AuditEvent>(builder =>
        {
            builder.Property<Guid>(nameof(AuditEvent.Id))
                .ValueGeneratedNever()
                .HasColumnType("uuid")
                .HasColumnName("id");

            builder.Property<Guid?>(nameof(AuditEvent.ActorClientId))
                .HasColumnType("uuid")
                .HasColumnName("actor_client_id");

            builder.Property<Guid?>(nameof(AuditEvent.SubjectClientId))
                .HasColumnType("uuid")
                .HasColumnName("subject_client_id");

            builder.Property<Guid>(nameof(AuditEvent.CorrelationId))
                .HasColumnType("uuid")
                .HasColumnName("correlation_id");

            builder.Property<string>(nameof(AuditEvent.Details))
                .HasMaxLength(1024)
                .HasColumnType("varchar")
                .HasColumnName("details");

            builder.Property<string>(nameof(AuditEvent.EventType))
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("varchar")
                .HasColumnName("event_type");

            builder.Property<Guid?>(nameof(AuditEvent.LeaseId))
                .HasColumnType("uuid")
                .HasColumnName("lease_id");

            builder.Property<DateTimeOffset>(nameof(AuditEvent.OccurredAtUtc))
                .HasColumnType("timestamp with time zone")
                .HasColumnName("occurred_at_utc");

            builder.Property<string>(nameof(AuditEvent.Outcome))
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("varchar")
                .HasColumnName("outcome");

            builder.Property<string>(nameof(AuditEvent.TargetId))
                .HasMaxLength(128)
                .HasColumnType("varchar")
                .HasColumnName("target_id");

            builder.HasKey(nameof(AuditEvent.Id));
            builder.HasIndex(nameof(AuditEvent.CorrelationId)).HasDatabaseName("idx_audit_events_correlation_id");
            builder.HasIndex(nameof(AuditEvent.OccurredAtUtc)).HasDatabaseName("idx_audit_events_occurred_at");
            builder.HasIndex(nameof(AuditEvent.TargetId), nameof(AuditEvent.OccurredAtUtc)).HasDatabaseName("idx_audit_events_target_time");
            builder.ToTable("audit_events");
        });

        modelBuilder.Entity<BackupLease>(builder =>
        {
            builder.Property<Guid>(nameof(BackupLease.Id))
                .ValueGeneratedNever()
                .HasColumnType("uuid")
                .HasColumnName("id");

            builder.Property<Guid>(nameof(BackupLease.ClientId))
                .HasColumnType("uuid")
                .HasColumnName("client_id");

            builder.Property<DateTimeOffset>(nameof(BackupLease.CreatedAtUtc))
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at_utc");

            builder.Property<DateTimeOffset>(nameof(BackupLease.LastHeartbeatAtUtc))
                .HasColumnType("timestamp with time zone")
                .HasColumnName("last_heartbeat_at_utc");

            builder.Property<DateTimeOffset?>(nameof(BackupLease.ReleasedAtUtc))
                .HasColumnType("timestamp with time zone")
                .HasColumnName("released_at_utc");

            builder.Property<BackupLeaseState>(nameof(BackupLease.State))
                .HasColumnType("integer")
                .HasColumnName("state");

            builder.Property<string>(nameof(BackupLease.TargetId))
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("varchar")
                .HasColumnName("target_id");

            builder.HasKey(nameof(BackupLease.Id));
            builder.HasIndex(nameof(BackupLease.ClientId), nameof(BackupLease.TargetId)).HasDatabaseName("idx_backup_leases_client_target");
            builder.HasIndex(nameof(BackupLease.TargetId), nameof(BackupLease.State)).HasDatabaseName("idx_backup_leases_target_state");
            builder.ToTable("backup_leases", null, table =>
            {
                table.HasCheckConstraint("ck_backup_leases_heartbeat_time", "last_heartbeat_at_utc >= created_at_utc");
                table.HasCheckConstraint(
                    "ck_backup_leases_release_state",
                    "(state = 1 AND released_at_utc IS NULL) OR (state IN (2, 3) AND released_at_utc IS NOT NULL)");
                table.HasCheckConstraint("ck_backup_leases_state", "state IN (1, 2, 3)");
            });
        });

        modelBuilder.Entity<TargetRuntimeObservation>(builder =>
        {
            builder.Property<Guid>(nameof(TargetRuntimeObservation.Id))
                .ValueGeneratedNever()
                .HasColumnType("uuid")
                .HasColumnName("id");

            builder.Property<DateTimeOffset>(nameof(TargetRuntimeObservation.ObservedAtUtc))
                .HasColumnType("timestamp with time zone")
                .HasColumnName("observed_at_utc");

            builder.Property<TargetLifecycleState>(nameof(TargetRuntimeObservation.State))
                .HasColumnType("integer")
                .HasColumnName("state");

            builder.Property<string>(nameof(TargetRuntimeObservation.TargetId))
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("varchar")
                .HasColumnName("target_id");

            builder.HasKey(nameof(TargetRuntimeObservation.Id));
            builder.HasIndex(nameof(TargetRuntimeObservation.TargetId))
                .IsUnique()
                .HasDatabaseName("ux_target_runtime_observations_target");
            builder.ToTable("target_runtime_observations");
        });

        modelBuilder.Entity<TargetGrant>(builder =>
        {
            builder.Property<Guid>(nameof(TargetGrant.Id))
                .ValueGeneratedNever()
                .HasColumnType("uuid")
                .HasColumnName("id");

            builder.Property<Guid>(nameof(TargetGrant.ClientId))
                .HasColumnType("uuid")
                .HasColumnName("client_id");

            builder.Property<string>(nameof(TargetGrant.TargetId))
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("varchar")
                .HasColumnName("target_id");

            builder.HasKey(nameof(TargetGrant.Id));
            builder.HasIndex(nameof(TargetGrant.ClientId), nameof(TargetGrant.TargetId))
                .IsUnique()
                .HasDatabaseName("ux_target_grants_client_target");
            builder.ToTable("target_grants");
        });

        modelBuilder.Entity<IdentityRole<Guid>>(builder =>
        {
            builder.Property<Guid>(role => role.Id)
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            builder.Property<string>(role => role.ConcurrencyStamp)
                .IsConcurrencyToken()
                .HasColumnType("text");

            builder.Property<string>(role => role.Name)
                .HasMaxLength(256)
                .HasColumnType("character varying(256)");

            builder.Property<string>(role => role.NormalizedName)
                .HasMaxLength(256)
                .HasColumnType("character varying(256)");

            builder.HasKey(role => role.Id);
            builder.HasIndex(role => role.NormalizedName)
                .IsUnique()
                .HasDatabaseName("RoleNameIndex");
            builder.ToTable("AspNetRoles");
        });

        modelBuilder.Entity<IdentityRoleClaim<Guid>>(builder =>
        {
            builder.Property<int>(claim => claim.Id)
                .ValueGeneratedOnAdd()
                .HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(builder.Property<int>(claim => claim.Id));

            builder.Property<string>(claim => claim.ClaimType).HasColumnType("text");
            builder.Property<string>(claim => claim.ClaimValue).HasColumnType("text");
            builder.Property<Guid>(claim => claim.RoleId).HasColumnType("uuid");

            builder.HasKey(claim => claim.Id);
            builder.HasIndex(claim => claim.RoleId);
            builder.ToTable("AspNetRoleClaims");
        });

        modelBuilder.Entity<IdentityUser<Guid>>(builder =>
        {
            builder.Property<Guid>(user => user.Id)
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            builder.Property<int>(user => user.AccessFailedCount).HasColumnType("integer");
            builder.Property<string>(user => user.ConcurrencyStamp).IsConcurrencyToken().HasColumnType("text");
            builder.Property<string>(user => user.Email).HasMaxLength(256).HasColumnType("character varying(256)");
            builder.Property<bool>(user => user.EmailConfirmed).HasColumnType("boolean");
            builder.Property<bool>(user => user.LockoutEnabled).HasColumnType("boolean");
            builder.Property<DateTimeOffset?>(user => user.LockoutEnd).HasColumnType("timestamp with time zone");
            builder.Property<string>(user => user.NormalizedEmail).HasMaxLength(256).HasColumnType("character varying(256)");
            builder.Property<string>(user => user.NormalizedUserName).HasMaxLength(256).HasColumnType("character varying(256)");
            builder.Property<string>(user => user.PasswordHash).HasColumnType("text");
            builder.Property<string>(user => user.PhoneNumber).HasColumnType("text");
            builder.Property<bool>(user => user.PhoneNumberConfirmed).HasColumnType("boolean");
            builder.Property<string>(user => user.SecurityStamp).HasColumnType("text");
            builder.Property<bool>(user => user.TwoFactorEnabled).HasColumnType("boolean");
            builder.Property<string>(user => user.UserName).HasMaxLength(256).HasColumnType("character varying(256)");

            builder.HasKey(user => user.Id);
            builder.HasIndex(user => user.NormalizedEmail).HasDatabaseName("EmailIndex");
            builder.HasIndex(user => user.NormalizedUserName).IsUnique().HasDatabaseName("UserNameIndex");
            builder.ToTable("AspNetUsers");
        });

        modelBuilder.Entity<IdentityUserClaim<Guid>>(builder =>
        {
            builder.Property<int>(claim => claim.Id)
                .ValueGeneratedOnAdd()
                .HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(builder.Property<int>(claim => claim.Id));

            builder.Property<string>(claim => claim.ClaimType).HasColumnType("text");
            builder.Property<string>(claim => claim.ClaimValue).HasColumnType("text");
            builder.Property<Guid>(claim => claim.UserId).HasColumnType("uuid");

            builder.HasKey(claim => claim.Id);
            builder.HasIndex(claim => claim.UserId);
            builder.ToTable("AspNetUserClaims");
        });

        modelBuilder.Entity<IdentityUserLogin<Guid>>(builder =>
        {
            builder.Property<string>(login => login.LoginProvider).HasColumnType("text");
            builder.Property<string>(login => login.ProviderKey).HasColumnType("text");
            builder.Property<string>(login => login.ProviderDisplayName).HasColumnType("text");
            builder.Property<Guid>(login => login.UserId).HasColumnType("uuid");

            builder.HasKey(login => new { login.LoginProvider, login.ProviderKey });
            builder.HasIndex(login => login.UserId);
            builder.ToTable("AspNetUserLogins");
        });

        modelBuilder.Entity<IdentityUserRole<Guid>>(builder =>
        {
            builder.Property<Guid>(userRole => userRole.UserId).HasColumnType("uuid");
            builder.Property<Guid>(userRole => userRole.RoleId).HasColumnType("uuid");

            builder.HasKey(userRole => new { userRole.UserId, userRole.RoleId });
            builder.HasIndex(userRole => userRole.RoleId);
            builder.ToTable("AspNetUserRoles");
        });

        modelBuilder.Entity<IdentityUserToken<Guid>>(builder =>
        {
            builder.Property<Guid>(token => token.UserId).HasColumnType("uuid");
            builder.Property<string>(token => token.LoginProvider).HasColumnType("text");
            builder.Property<string>(token => token.Name).HasColumnType("text");
            builder.Property<string>(token => token.Value).HasColumnType("text");

            builder.HasKey(token => new { token.UserId, token.LoginProvider, token.Name });
            builder.ToTable("AspNetUserTokens");
        });

        modelBuilder.Entity<TargetGrant>(builder =>
        {
            builder.HasOne(grant => grant.Client)
                .WithMany()
                .HasForeignKey(grant => grant.ClientId)
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired()
                .HasConstraintName("fk_target_grants_client_id");

            builder.Navigation(grant => grant.Client);
        });

        modelBuilder.Entity<IdentityRoleClaim<Guid>>(builder =>
        {
            builder.HasOne<IdentityRole<Guid>>()
                .WithMany()
                .HasForeignKey(claim => claim.RoleId)
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity<IdentityUserClaim<Guid>>(builder =>
        {
            builder.HasOne<IdentityUser<Guid>>()
                .WithMany()
                .HasForeignKey(claim => claim.UserId)
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity<IdentityUserLogin<Guid>>(builder =>
        {
            builder.HasOne<IdentityUser<Guid>>()
                .WithMany()
                .HasForeignKey(login => login.UserId)
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity<IdentityUserRole<Guid>>(builder =>
        {
            builder.HasOne<IdentityRole<Guid>>()
                .WithMany()
                .HasForeignKey(userRole => userRole.RoleId)
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            builder.HasOne<IdentityUser<Guid>>()
                .WithMany()
                .HasForeignKey(userRole => userRole.UserId)
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity<IdentityUserToken<Guid>>(builder =>
        {
            builder.HasOne<IdentityUser<Guid>>()
                .WithMany()
                .HasForeignKey(token => token.UserId)
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });
#pragma warning restore 612, 618
    }
}
